import type { SemgrepRule } from './index'

export const BUILTIN_RULES: SemgrepRule[] = [
  {
    id: 'SS-SHELL-001',
    patternRegex: 'rm\\s+-(?:rf|fr)\\s+/',
    message: 'Dangerous rm -rf / command that recursively deletes all files',
    severity: 'CRITICAL',
    languages: ['bash', 'shell', 'generic'],
  },
  {
    id: 'SS-SHELL-002',
    patternRegex: 'curl\\s+.*\\|\\s*(?:sh|bash)',
    message: 'Remote script execution via curl pipe to shell',
    severity: 'CRITICAL',
    languages: ['bash', 'shell', 'generic'],
  },
  {
    id: 'SS-SHELL-003',
    patternRegex: 'wget\\s+.*\\|\\s*(?:sh|bash)',
    message: 'Remote script execution via wget pipe to shell',
    severity: 'CRITICAL',
    languages: ['bash', 'shell', 'generic'],
  },
  {
    id: 'SS-SECRET-001',
    patternRegex: 'sk-[A-Za-z0-9]{20,}',
    message: 'Hardcoded OpenAI API key detected',
    severity: 'CRITICAL',
    languages: ['generic'],
  },
  {
    id: 'SS-SECRET-002',
    patternRegex: '(?:ghp_|gho_|ghu_|ghs_|ghr_)[A-Za-z0-9]{36}',
    message: 'Hardcoded GitHub token detected',
    severity: 'CRITICAL',
    languages: ['generic'],
  },
  {
    id: 'SS-SECRET-003',
    patternRegex: '-----BEGIN\\s+(?:RSA\\s+)?PRIVATE\\s+KEY-----',
    message: 'Hardcoded private key detected',
    severity: 'CRITICAL',
    languages: ['generic'],
  },
  {
    id: 'SS-FS-001',
    pattern: 'fs.rmSync',
    message: 'Dangerous file system operation with recursive delete',
    severity: 'ERROR',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'SS-FS-002',
    patternRegex: 'chmod\\s+777\\s+',
    message: 'World-writable file permissions set',
    severity: 'ERROR',
    languages: ['bash', 'shell', 'generic'],
  },
  {
    id: 'SS-NET-001',
    patternRegex: '(?:curl|wget|fetch|axios\\.get)\\s+\\(?\\s*[\'"]https?://',
    message: 'External network request detected',
    severity: 'WARNING',
    languages: ['bash', 'shell', 'generic'],
  },
  {
    id: 'SS-OBF-001',
    patternRegex: 'eval\\s*\\(\\s*(?:atob|Buffer\\.from|unescape|decodeURIComponent)',
    message: 'Obfuscated code execution via eval with encoded input',
    severity: 'ERROR',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'SS-OBF-002',
    patternRegex: 'String\\.fromCharCode\\s*\\(\\d+\\s*,\\s*\\d+',
    message: 'Obfuscated string construction via fromCharCode',
    severity: 'WARNING',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'SS-EXEC-001',
    pattern: 'child_process.exec',
    message: 'Child process execution detected',
    severity: 'ERROR',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'SS-EXEC-002',
    patternRegex: 'subprocess\\.(?:Popen|call|run)\\(.*shell\\s*=\\s*True',
    message: 'Shell execution via Python subprocess with shell=True',
    severity: 'ERROR',
    languages: ['python'],
  },
  {
    id: 'SS-ENV-001',
    patternRegex: 'process\\.env\\.(?:AWS_SECRET|SECRET|PASSWORD|API_KEY|TOKEN)',
    message: 'Sensitive environment variable access detected',
    severity: 'WARNING',
    languages: ['javascript', 'typescript'],
  },
  {
    id: 'SS-CODE-001',
    pattern: 'eval(',
    message: 'Arbitrary code execution via eval()',
    severity: 'ERROR',
    languages: ['javascript', 'typescript'],
  },
]
